AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  WebCrawlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: webcrawler/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 10
